"""
Google Calendar Integration for Librarian AI.
Automatically schedules follow-up review events for Job opportunities (Tomorrow @ 9:00 AM).
"""

from datetime import datetime, timedelta, timezone
import logging
from pathlib import Path
from typing import Any, Dict, Optional

from config import settings
from utils import log_execution, measure_performance

logger = logging.getLogger("librarian.calendar")

# Google API client imports (optional / graceful fallback if missing)
try:
    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow
    from googleapiclient.discovery import build
    from googleapiclient.errors import HttpError
    GOOGLE_CALENDAR_AVAILABLE = True
except ImportError:
    GOOGLE_CALENDAR_AVAILABLE = False
    logger.warning("Google Calendar libraries not installed. Calendar event creation will be simulated.")

SCOPES = ["https://www.googleapis.com/auth/calendar.events"]


class CalendarManager:
    """Manages Google Calendar authentication and event scheduling for Jobs."""

    def __init__(
        self,
        credentials_path: Optional[Path] = None,
        token_path: Optional[Path] = None,
        **kwargs: Any,
    ) -> None:
        self.credentials_path: Path = Path(
            credentials_path or settings.google_calendar_credentials_path
        ).resolve()
        self.token_path: Path = Path(
            token_path or settings.google_calendar_token_path
        ).resolve()
        self._service: Optional[Any] = None

    def _get_service(self) -> Optional[Any]:
        """Authenticate and return Google Calendar service resource."""
        if not GOOGLE_CALENDAR_AVAILABLE:
            return None

        if self._service:
            return self._service

        creds: Optional[Credentials] = None

        if self.token_path.exists():
            try:
                creds = Credentials.from_authorized_user_file(str(self.token_path), SCOPES)
            except Exception as e:
                logger.warning("Error reading token file from %s: %s", self.token_path, e)

        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                try:
                    creds.refresh(Request())
                    with open(self.token_path, "w", encoding="utf-8") as token_file:
                        token_file.write(creds.to_json())
                except Exception as e:
                    logger.warning("Failed to refresh Google Calendar token: %s", e)
                    creds = None
            elif self.credentials_path.exists():
                try:
                    flow = InstalledAppFlow.from_client_secrets_file(str(self.credentials_path), SCOPES)
                    creds = flow.run_local_server(port=0)
                    with open(self.token_path, "w", encoding="utf-8") as token_file:
                        token_file.write(creds.to_json())
                except Exception as e:
                    logger.warning("OAuth flow failed for Google Calendar: %s", e)
                    creds = None
            else:
                logger.debug(
                    "Google Calendar credentials not found at %s. Skipping live API connection.",
                    self.credentials_path,
                )
                return None

        if creds and creds.valid:
            try:
                self._service = build("calendar", "v3", credentials=creds)
                return self._service
            except Exception as e:
                logger.error("Failed to build Google Calendar service: %s", e)
                return None

        return None

    @measure_performance
    def create_job_event(
        self,
        title: str,
        url: str,
        **kwargs: Any,
    ) -> Optional[Dict[str, Any]]:
        """
        Creates a calendar reminder event for a Job Opportunity scheduled
        for Tomorrow @ 9:00 AM in the user's local timezone.
        """
        now = datetime.now()
        # Schedule for tomorrow at 09:00:00 AM
        tomorrow_9am = (now + timedelta(days=1)).replace(hour=9, minute=0, second=0, microsecond=0)
        end_930am = tomorrow_9am + timedelta(minutes=30)

        # Local timezone offset ISO 8601 formatting
        start_iso = tomorrow_9am.isoformat()
        end_iso = end_930am.isoformat()

        notes = kwargs.get("notes", "")
        summary = f"💼 Review Job: {title}"
        description = (
            f"Review Job Opportunity:\n\n"
            f"Title: {title}\n"
            f"URL: {url}\n"
            f"Notes: {notes}\n\n"
            f"---\nGenerated by Librarian AI"
        )

        event_body = {
            "summary": summary,
            "description": description,
            "start": {
                "dateTime": start_iso,
                "timeZone": str(now.astimezone().tzinfo) or "UTC",
            },
            "end": {
                "dateTime": end_iso,
                "timeZone": str(now.astimezone().tzinfo) or "UTC",
            },
            "reminders": {
                "useDefault": False,
                "overrides": [
                    {"method": "popup", "minutes": 15},
                    {"method": "email", "minutes": 60},
                ],
            },
        }

        service = self._get_service()
        if not service:
            logger.info(
                "[CALENDAR SIMULATION] Would create event '%s' for tomorrow at 09:00 AM (Link: %s)",
                summary, url
            )
            return {"simulated": True, "event": event_body}

        try:
            created_event = service.events().insert(calendarId="primary", body=event_body).execute()
            logger.info("Successfully scheduled Google Calendar event: %s", created_event.get("htmlLink"))
            return created_event
        except Exception as e:
            logger.error("Failed to insert Google Calendar event: %s", e)
            return None


calendar_manager = CalendarManager()
